services:
  # Backend Service
  - type: web
    name: novatech-ai-backend
    env: python
    plan: starter  # Changed from free to starter for more memory
    buildCommand: |
      pip install -r requirements.txt
      pip install gunicorn
    startCommand: gunicorn backend_server_production:app -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT --workers 1 --max-requests 1000 --max-requests-jitter 100 --timeout 120 --keep-alive 5
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: PORT
        value: 8000
      - key: HOST
        value: 0.0.0.0
      - key: GOOGLE_API_KEY
        sync: false
      - key: NEWS_API_KEY
        sync: false
      - key: ALPHA_VANTAGE_API_KEY
        sync: false
      - key: FINNHUB_API_KEY
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: PYTHONDONTWRITEBYTECODE
        value: "1"
    healthCheckPath: /health
    autoDeploy: true
    branch: main

  # Frontend Service
  - type: web
    name: novatech-ai-frontend
    env: static
    plan: starter
    buildCommand: |
      cd frontend
      npm install
      npm run build
    staticPublishPath: ./frontend/build
    envVars:
      - key: REACT_APP_API_URL
        value: https://novatech-ai-backend.onrender.com
    autoDeploy: true
    branch: main 
