services:
  - type: web
    name: novatech-ai-backend
    env: python
    plan: starter
    buildCommand: |
      pip install -r requirements.txt
      pip install gunicorn
    startCommand: gunicorn backend_server:app -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: PORT
        value: 8000
      - key: HOST
        value: 0.0.0.0
      - key: GOOGLE_API_KEY
        sync: false
      - key: NEWS_API_KEY
        sync: false
      - key: ALPHA_VANTAGE_API_KEY
        sync: false
      - key: FINNHUB_API_KEY
        sync: false
      - key: OPENAI_API_KEY
        sync: false
    healthCheckPath: /health
    autoDeploy: true
    branch: main 